
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt
from math import *

x, y =np.loadtxt("remd_3419800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='crimson', label="10.20")
x, y =np.loadtxt("remd_3406100.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkblue', label="11.01")
x, y =np.loadtxt("remd_1004100.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='deepskyblue', label="11.30")
x, y =np.loadtxt("remd_3386400.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkred', label="12.01")
x, y =np.loadtxt("remd_3290700.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkcyan', label="13.01")
x, y =np.loadtxt("remd_3279500.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkgreen', label="14.01")
plt.legend(loc='lower left')
plt.title("I(Q) vs Q")
plt.xlabel("Q")
plt.ylabel("I(Q)")
plt.show()
x, y =np.loadtxt("remd_3234900.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkorchid', label="15.01")
x, y =np.loadtxt("remd_1676200.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkturquoise', label="16.01")
x, y =np.loadtxt("remd_1530500.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='darkviolet', label="17.01")
x, y =np.loadtxt("remd_1028500.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='deeppink', label="18.01")
x, y =np.loadtxt("remd_114800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='dimgrey', label="19.01")
x, y =np.loadtxt("remd_11044800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='aquamarine', label="20.01")
x, y =np.loadtxt("remd_11020700.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='azure', label="21.01")
x, y =np.loadtxt("remd_10973100.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='brown', label="22.01")
x, y =np.loadtxt("remd_10963600.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='red', label="23.01")
x, y =np.loadtxt("remd_10736800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='blue', label="24.01")
x, y =np.loadtxt("remd_10254600.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='pink', label="25.01")
x, y =np.loadtxt("remd_8723800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='cadetblue', label="26.01")
x, y =np.loadtxt("remd_11109200.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='aqua', label="27.01")
x, y =np.loadtxt("remd_11481200.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='antiquewhite', label="28.01")
x, y =np.loadtxt("remd_8719900.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='pink', label="29.01")
x, y =np.loadtxt("remd_11743800.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='AliceBlue', label="30.04")
x, y =np.loadtxt("remd_5640400.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='cyan', label="31.07")
x, y =np.loadtxt("remd_8760700.int", skiprows=1, usecols =(0, 2), unpack=True )
plt.semilogy(x, y, color='purple', label="33.03")

plt.legend(loc='lower left')
plt.title("I(Q) vs Q")
plt.xlabel("Q")
plt.ylabel("I(Q)")
plt.show()
